### ISSUE TITLE
GNOME Shell Theme

### ISSUE THREAD

**Issue by MichaelTunnell** [B00merang-Project/Unity-8#2]
This looks very interesting and I will be using it for an article I'm writing (which will be published in a couple of days) but I need a GNOME Shell theme for the article.

I saw that you have plans to make a GNOME Shell theme so I was just curious, what is the timeline for it?

**Comment by Elbullazul** [comment]
@MichaelTunnell maybe a week or two, I have to install an actual gnome distro (probably fedora) on my machine. I could use a VM but it's a big hassle to work with two OSes running

**Comment by MichaelTunnell** [comment]
That's fine . . . if Unity 7 is done sooner then that would be better for my article and then whenever Unity 8 is finished I can update the article to link to that one too.

**Comment by Elbullazul** [comment]
I included the United Gnome theme, it's way easier than to do the thing from scratch (just a mod or two to make it closer to real unity)

**Comment by MichaelTunnell** [comment]
Sounds good to me

**Comment by cinnamoner** [comment]
@MichaelTunnell This is as good a time as any to say thank you for everything you're doing. You're an awesome guy.
