### ISSUE TITLE
Thoughts on a Unity 7 theme?

### ISSUE THREAD

**Issue by MichaelTunnell** [B00merang-Project/Unity-8#3]
I think it might be beneficial for people who want to keep something similar to what they already have.

Here is an example of an [Ambiance theme for GNOME Shell](https://www.gnome-look.org/content/show.php/Ambiance-Gnome?content=166632) (3.14) based on Unity 7 so it might be able to be used as a foundation if desired.

**Comment by Elbullazul** [comment]
@MichaelTunnell I don't know, many other artists work on other iterations of ambiance. Up to now, Ravefinity made a decent job for cross-platform support but they ended development for some obscure reason. Maybe I can pack a theme up, but maintenance may be a bit difficult.

this concerns the GTK 3 part. Because otherwise I would be OK maintaining Shell themes (Gnome, Cinnamon, Xfce/Mate?)

how would you suggest we manage the GTK part? (tried telegram but don't have a cellphone :/)

**Comment by ghost** [comment]
👂

**Comment by Elbullazul** [comment]
@MichaelTunnell I may start development soon, just have to fix the laptop, a weird issue of Mint using BIOS-boot and Fedora using EFI

**Comment by cinnamoner** [comment]
> don't have a cellphone :/

@Elbullazul 

> Blessed are the people without a cellphone and even more blessed those without a smartphone.

R. Addison

**Comment by MichaelTunnell** [comment]
> I don't know, many other artists work on other iterations of ambiance. Up to now, Ravefinity made a decent job for cross-platform support but they ended development for some obscure reason.

The reason is not obscure. The reason is GNOME is an incredibly frustrating project to stay up to date with. They break support for GNOME Shell themes and they break support for GTK themes so often I abandoned my own projects regarding GNOME Extensions.

> Maybe I can pack a theme up, but maintenance may be a bit difficult.

I don't really care if the GTK theme is perfect . . . it could be a modified version of Numix for all I care. :)

I just asked because I wanted to see if it would be possible to get it close and all of the themes that previously existed don't exist anymore and I saw you already started a Unity 8 theme.

> how would you suggest we manage the GTK part?

I have no idea. I don't really know what the problem with GTK is other than it changes all the time.

>  (tried telegram but don't have a cellphone :/)

We you mention Telegram are you referring to managing the theme or just in general?

If in general, then I'd suggest Matrix+Riot or Wire.com, neither require a phone number.

-------

> I may start development soon

That sounds great . . . I want to write the article soon and if you can help out with the theme stuff for it then I will certainly promote the project in the article.

> just have to fix the laptop, a weird issue of Mint using BIOS-boot and Fedora using EFI

sounds like Mint being crappy again . . . like normal for Mint. :)

**Comment by Elbullazul** [comment]
@MichaelTunnell yeah, I just dumped the whole mint setup. Will probably use another machine for cinnamon development. Or move to arch, although not 'real arch' right away

I'll just import a GTK theme from another project and present the thing as a 'Unity retrocompatibility package' :smile:

**Comment by MichaelTunnell** [comment]
> I just dumped the whole mint setup. Will probably use another machine for cinnamon development. Or move to arch, although not 'real arch' right away

Antergos is an option from a completely unbiased suggestion. :)

> I'll just import a GTK theme from another project and present the thing as a 'Unity retrocompatibility package'

That works. I just cant write about a deprecated theme so if you fork it, I doubt they would care since they deprecated it anyway. :)

**Comment by cinnamoner** [comment]
> Blessed are the people who are dealing with qt and not so blessed those who are dealing with gtk.

Me

At any rate, good luck on this project. It serves a good purpose.

**Comment by cinnamoner** [comment]
I wouldn't move to Arch. Arch is a purpose in itself. If you see the OS as a purpose, then it's for you. If you need it for a tool, then it's not for you. Make sure you check the forums before each update. Arch is kinda OS art. It's serves no practical purpose just as an ice sculpture serves none. Rather sooner than later, it melts down.

**Comment by Elbullazul** [comment]
@MichaelTunnell I ended up using @bluedxca93 's ambiance theme. Here are some screenies:

![capture d ecran de 2017-04-13 13-45-22](https://cloud.githubusercontent.com/assets/15310985/25017141/a295c4e0-2050-11e7-9c79-a77cb5f082de.png)
![capture d ecran de 2017-04-13 13-45-27](https://cloud.githubusercontent.com/assets/15310985/25017139/a290dff2-2050-11e7-9e29-a07cc9d082b1.png)
![capture du 2017-04-13 13-45-51](https://cloud.githubusercontent.com/assets/15310985/25017140/a29538fe-2050-11e7-804c-32cea21cb817.png)

**Comment by Elbullazul** [comment]
https://github.com/B00merang-Project/Unity7

**Comment by MichaelTunnell** [comment]
Wow dude . . . this is GREAT! That was super fast. I will try to get the article done for publishing on Monday or Tuesday. Thank you so much for this!
