### ISSUE TITLE
White screen in gnome 3.26

### ISSUE THREAD

**Issue by cgiannakidis70** [B00merang-Project/Unity-8#4]
Applying the theme in ubuntu 18.04 (development branch) with tweak tools (for applications theme)  there is a white screen instead of wallpaper.Gnome version 3.26.2.

**Comment by Elbullazul** [comment]
can you post a screenshot of the issue? Does changing the wallpaper fix it?

**Comment by cgiannakidis70** [comment]
![screenshot from 2017-11-21 20-03-23](https://user-images.githubusercontent.com/33185625/33088749-34ab1dd0-cef7-11e7-94b7-614bcdafb202.png)
Changing wallpaper does not fix the problem.

**Comment by Elbullazul** [comment]
does killing off nautilus fixes the problem?

> killall nautilus

**Comment by cgiannakidis70** [comment]
Hi.
I did something else.I deactivated "Show Icons on Desktop "  from tweak tool, and the wallpaper is back.The problem is fixed.But with the selection "Show icons " active, it remains.

**Comment by Elbullazul** [comment]
had something similar happen on linux mint some time ago.

Will check this out, although it may be due to the nautilus version still being developed and updated

**Comment by cgiannakidis70** [comment]
OK.
Thanks.

**Comment by cgiannakidis70** [comment]
Hi again.
I tried in ubuntu 17.10 with gnome 3.26.2 and it is the same thing.

**Comment by Elbullazul** [comment]
fixed (very late but at least it's fixed)
